# Generated by Django 4.2.6 on 2023-10-19 19:20

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AltCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Ekleyin')),
                ('kisaltma', models.CharField(max_length=2, verbose_name='Alt Kategori Kısıltması')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Ekleyin')),
                ('kisaltma', models.CharField(max_length=2, verbose_name='Kategori Kısıltması')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ürün Başlığı Giriniz')),
                ('price', models.FloatField(verbose_name='Ürün Fiyatı')),
                ('sale_price', models.FloatField(blank=True, null=True, verbose_name='Ürün İndirimli Fiyatı')),
                ('is_home', models.BooleanField(default=True, verbose_name='Ürün Ana Sayfada Gösterilsin Mi?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ürün Mevcut Mu?')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Ürün İndirimli Mi?')),
                ('is_yeni', models.BooleanField(verbose_name='Ürün Yeni Mi?')),
                ('img', models.ImageField(upload_to='', verbose_name='ürün Detay 3. Resmi')),
                ('description', models.TextField(verbose_name='Ürün Açıklama')),
                ('urun_ayrinti', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ürün Ayrıtılı Bilgi')),
                ('boy', models.IntegerField(blank=True, verbose_name='Ürün Boyu Cm')),
                ('agirlik', models.IntegerField(blank=True, verbose_name='Ürün Ağırlık Cm')),
                ('uzunluk', models.IntegerField(blank=True, verbose_name='Ürün Boyu Cm')),
                ('genislik', models.IntegerField(blank=True, verbose_name='Ürün Genişlik Cm')),
                ('derinlik', models.IntegerField(blank=True, verbose_name='Ürün Derinlik Cm')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ürün Eklenme Tarihi')),
                ('upgrade_date', models.DateTimeField(auto_now=True, verbose_name='Ürün Güncellenme Tarihi')),
                ('stok', models.IntegerField(verbose_name='Stok Adeti')),
                ('indirimoran', models.IntegerField(null=True, verbose_name='İndirim Oranı Yüzde Kaç?')),
                ('cok_satan', models.BooleanField(verbose_name='Çok Satanlarda Mı?')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('altcategory', models.ManyToManyField(blank=True, to='products.altcategory', verbose_name='Ürün Alt Kategori Giriniz?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Ürün Kategori Giriniz?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ürün Ekleyen')),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
    ]
