# Generated by Django 4.2.6 on 2023-10-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altcategory',
            name='kisaltma',
            field=models.CharField(max_length=2, unique=True, verbose_name='Alt Kategori Kısıltması'),
        ),
        migrations.AlterField(
            model_name='altcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kategori Ekleyin'),
        ),
        migrations.AlterField(
            model_name='category',
            name='kisaltma',
            field=models.CharField(max_length=2, unique=True, verbose_name='Kategori Kısıltması'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kategori Ekleyin'),
        ),
    ]
