# Generated by Django 4.2.6 on 2023-10-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_altcategory_kisaltma_alter_altcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='product/%Y/%m/%d/', verbose_name='ürün Detay 3. Resmi'),
        ),
    ]
