# Generated by Django 4.2.6 on 2023-10-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(default=1, upload_to='product/%Y/%m/%d/', verbose_name='ürün Detay 1. Resmi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(default=1, upload_to='product/%Y/%m/%d/', verbose_name='ürün Detay 2. Resmi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(default=1, upload_to='product/%Y/%m/%d/', verbose_name='ürün Detay 3. Resmi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='product/%Y/%m/%d/', verbose_name='ürün Ana Resmi'),
        ),
    ]
