# Generated by Django 4.0.1 on 2023-10-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_indirimoran'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marka',
            field=models.CharField(max_length=50, null=True, verbose_name='Ürün Markası Girin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='altcategory',
            field=models.ManyToManyField(blank=True, to='products.AltCategory', verbose_name='Ürün Alt Kategori Giriniz?'),
        ),
    ]
