# Generated by Django 4.0.1 on 2023-10-22 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_markamodel_alter_altcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='indirimoran',
            field=models.IntegerField(blank=True, null=True, verbose_name='İndirim Oranı Yüzde Kaç?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.markamodel', verbose_name='Ürün Markası Girin'),
        ),
    ]
