# Generated by Django 4.0.1 on 2023-10-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_indirimoran_alter_product_marka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='indirimoran',
            field=models.IntegerField(blank=True, verbose_name='İndirim Oranı Yüzde Kaç?'),
        ),
    ]
