# Generated by Django 4.0.1 on 2023-10-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_indirimoran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='indirimoran',
            field=models.IntegerField(blank=True, null=True, verbose_name='İndirim Oranı Yüzde Kaç?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marka',
            field=models.CharField(max_length=50, verbose_name='Ürün Markası'),
        ),
        migrations.DeleteModel(
            name='MarkaModel',
        ),
    ]
