# Generated by Django 4.0.1 on 2023-10-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_markamodel_alter_altcategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_home',
            field=models.BooleanField(default=1, verbose_name='Ana Sayfada Gösterilsin Mi? (3 Adet Kategori Seçebilirsimiz)'),
            preserve_default=False,
        ),
    ]
