# Generated by Django 4.0.1 on 2023-10-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to='product/category/'),
            preserve_default=False,
        ),
    ]
