# Generated by Django 4.0.1 on 2023-11-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stokno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ürün Stok Numarası'),
        ),
    ]
