# Generated by Django 4.0.1 on 2023-11-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_stokno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stokno',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ürün Stok Numarası'),
        ),
    ]
