# Generated by Django 4.0.1 on 2023-11-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_stokno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='ürün Detay 1. Resmi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='ürün Detay 2. Resmi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='ürün Detay 3. Resmi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stok',
            field=models.IntegerField(verbose_name='Ürün Mevcut İse Stok Adedi Giriniz'),
        ),
    ]
