# Generated by Django 4.0.1 on 2023-11-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_img1_alter_product_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seodescription',
            field=models.TextField(null=True, verbose_name='Ürün Açıklama'),
        ),
        migrations.AddField(
            model_name='product',
            name='seotitle',
            field=models.CharField(max_length=200, null=True, verbose_name='Ürün Başlığı Giriniz'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Ürün Açıklama'),
        ),
    ]
