# Generated by Django 4.0.1 on 2023-11-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_seodescription_product_seotitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seodescription',
            field=models.TextField(null=True, verbose_name='Seo Açıklama Giriniz'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seotitle',
            field=models.CharField(max_length=200, null=True, verbose_name='Seo Başlığı Giriniz'),
        ),
    ]
