# Generated by Django 4.0.1 on 2023-11-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_seodescription_alter_product_seotitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stokno',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Ürün Stok Numarası'),
        ),
    ]
