# Generated by Django 4.0.1 on 2023-11-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_altcategory_kisaltma_remove_category_kisaltma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='altcategory',
            name='seotitle',
            field=models.CharField(max_length=60, null=True, verbose_name='Kategori Seo Title Gir'),
        ),
        migrations.AddField(
            model_name='category',
            name='seotitle',
            field=models.CharField(max_length=60, null=True, verbose_name='Kategori Seo Title Gir'),
        ),
        migrations.AddField(
            model_name='markamodel',
            name='seotitle',
            field=models.CharField(max_length=60, null=True, verbose_name='Kategori Seo Title Gir'),
        ),
    ]
