# Generated by Django 4.0.1 on 2023-11-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_altcategory_seotitle_category_seotitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='carousel/%Y/%m/%d/', verbose_name='Slider Resmi Ekle')),
            ],
        ),
        migrations.AlterField(
            model_name='altcategory',
            name='seodescription',
            field=models.CharField(max_length=160, null=True, verbose_name='AltKategori Seo Description Gir'),
        ),
        migrations.AlterField(
            model_name='altcategory',
            name='seotitle',
            field=models.CharField(max_length=60, null=True, verbose_name='AltKategori Seo Title Gir'),
        ),
        migrations.AlterField(
            model_name='markamodel',
            name='seotitle',
            field=models.CharField(max_length=60, null=True, verbose_name='Marka Seo Title Gir'),
        ),
    ]
