# Generated by Django 4.0.1 on 2023-11-05 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30, verbose_name='İsim :')),
                ('last_name', models.CharField(default='', max_length=20, verbose_name='Soyisim :')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Telefon :')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='E mail ')),
                ('password', models.CharField(default='', max_length=100, verbose_name='Parola :')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ürün Fiyatı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Ürün İndirimli Fiyatı'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('adress', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=11)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
